language: android
android:
  components:
    - platform-tools
    - build-tools-26.0.2
    - android-25
    - extra-android-m2repository
script:
  - ./gradlew build --continue
before_install:
  - chmod +x gradlew
  - mv app/google-services.tmp app/google-services.json

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
