language: android
env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-m2repository
    #- addon-google_apis-google-$ANDROID_API_LEVEL
    #- extra-google-google_play_services
    #- extra-android-support
    #- extra-google-m2repository
script:
  - ./gradlew clean assembleDebug check
before_install:
  - chmod +x gradlew
  - mv app/google-services.tmp app/google-services.json

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
