language: android
android:
  components:
    - platform-tools
    - build-tools-26.0.2
    - android-25
    - extra-android-m2repository
script:
  - ./gradlew build
before_install:
  - chmod +x gradlew
  - mv app/google-services.tmp app/google-services.json